Accounts/urls.py
from django.urls import path
from .views import *

app_name='Accounts'
urlpatterns = [
    path("register/", register, name="register"),
    path("login/", login_user, name="login_user"),
    # path("logout_user/", logout_user, name="logout_user"),
]

Api/urls.py
from django.urls import path,include
from .views import *

app_name='Api'

urlpatterns = [
    path('',update,name='update'),
]

Attendance/urls.py
from django.urls import path,include
from .views import *

app_name='Attendance'

urlpatterns = [
    path('',index,name='index'),
    path('<int:date_id>/',detail,name='detail'),
]

LogMe/urls.py
from django.contrib import admin
from django.urls import path,include
from Accounts.views import home
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",home,name='home'),
    path("home/",home,name='home'),
    path("attendance/",include('Attendance.urls')),
    path("api/",include('Api.urls')),
    path("accounts/",include('Accounts.urls'))
]

Accounts/models.py
from django.db import models

# Create your models here.

Api/models.py
from django.db import models

# Create your models here.

Attendance/models.py
from django.db import models
from django.utils import timezone
# choices=('Present','Absent')
# Create your models here.


class Date(models.Model):
    date_id=models.AutoField(primary_key=True,auto_created=True)
    date = models.DateField(max_length=255,default=timezone.now)
    def __str__(self) -> str:
        return (self.date.strftime("%B %d %Y"))

class Attendance(models.Model):
    name = models.CharField(max_length=256,default='Victor')
    reg_no = models.IntegerField(default=100)
    period_1 = models.BooleanField(default=False)
    period_2 = models.BooleanField(default=False)
    period_3 = models.BooleanField(default=False)
    period_4 = models.BooleanField(default=False)
    period_5 = models.BooleanField(default=False)
    period_6 = models.BooleanField(default=False)
    period_7 = models.BooleanField(default=False)
    log_date= models.ForeignKey(Date,on_delete=models.CASCADE,related_name='attendances')
    def __str__(self):
        return f"{self.reg_no}-{self.log_date.date.strftime('%B %d %Y')}"

Accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.


def register(request):
    if request.method == 'POST':
        data = request.POST
        first_name = data['first_name']
        last_name = data['last_name']
        username = data['username']
        email = data['email']
        password = data['password']
        confirm_password = data['confirm_password']
        print(data)
        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username is already taken')
                return redirect('Accounts:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email is already taken')
                return redirect('Accounts:register')
            else:
                user = User.objects.create_user(username=username, password=password,
                                           email=email, first_name=first_name, last_name=last_name)
                user.save()
                return redirect('Accounts:login_user')
        else:
            messages.info(request, 'Password not matching!')
            return redirect('Accounts:register')
    else:
        return render(request, 'Accounts/register.html')


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Invalid Username or Password')
            return redirect('Accounts:login_user')

    else:
        return render(request, 'Accounts/login.html')

@login_required  
def home(request):
    return render(request,'home.html')

Api/views.py
from django.shortcuts import redirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from Attendance.models import Attendance, Date
import json
# Create your views here.
@csrf_exempt
def update(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        print(data)
        date_object = Date.objects.get(date=data['Date'])
        record = Attendance.objects.get(
            reg_no=data['Roll Number'], log_date=date_object.date_id)
        match int(data['Period ID']):
            case 1:
                record.period_1 = True
            case 2:
                record.period_2 = True
            case 3:
                record.period_3 = True
            case 4:
                record.period_4 = True
            case 5:
                record.period_5 = True
            case 6:
                record.period_6 = True
            case 7:
                record.period_7 = True
            case _:
                return HttpResponse("Invalid period id!")
        record.save()
        redirect(f'reverse(Attendance:detail)/{date_object.date_id}')
        return HttpResponse("Data recieved")
    else:
        return HttpResponse("API site")

Attendance/views.py
from django.shortcuts import render,get_list_or_404
from .models import Date
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def index(request):
    context={'date_list':get_list_or_404(Date)}
    return render(request,'Attendance/index.html',context=context)

@login_required
def detail(request,date_id):
    date=Date.objects.get(pk=date_id)
    attendance_objects=date.attendances.all().order_by("reg_no")
    data_list=[]
    for attendance in attendance_objects:
        data={}
        list=[attendance.period_1,
              attendance.period_2,
              attendance.period_3,
              attendance.period_4,
              attendance.period_5,
              attendance.period_6,
              attendance.period_7
            ]
        data['Name']=attendance.name
        data['Register Number']=attendance.reg_no
        data['Period 1']='Present' if attendance.period_1 else 'Absent'
        data['Period 2']='Present' if attendance.period_2 else 'Absent'
        data['Period 3']='Present' if attendance.period_3 else 'Absent'
        data['Period 4']='Present' if attendance.period_4 else 'Absent'
        data['Period 5']='Present' if attendance.period_5 else 'Absent'
        data['Period 6']='Present' if attendance.period_6 else 'Absent'
        data['Period 7']='Present' if attendance.period_7 else 'Absent'
        data['Status']=True if sum(list)>4 else False
        data_list.append(data)
    #data_list=sorted(data_list,key=lambda data:data["Register Number"])
    return render(request,'Attendance/detail.html',context={'data_list':data_list})

Accounts/templates/Accounts/login.html
{% extends 'base.html' %} {% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Login</title>
    <style>
      html,
      body {
        height: 100%;
      }

      .centre-parent {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 85%;
      }

      .form-control:focus {
        border-color: rgb(6, 175, 116);
        box-shadow: 0 0 5px rgb(0, 74, 46) !important;
      }

      .card,
      .card li {
        width: fit-content;
        background-color: rgb(197, 234, 219);
      }

      .form-floating {
        width: fit-content;
        display: flex;
        justify-content: center;
        padding: 0;
      }

      .list-group li {
        padding: 3vh 0;
      }

      .form-floating label {
        margin-left: 0%;
      }

      .card-body {
        width: fit-content;
      }

      form {
        display: flex;
        justify-content: center;
        flex-direction: column;
        align-items: center;
      }

      .list-group-item {
        border: none;
      }

      #login-btn {
        width: 100%;
      }
    </style>
  </head>
  <div class="centre-parent">
    <div class="card container py-2">
      <div class="card-body px-5">
        <ul class="list-group list-group-flush text-center">
          <li class="list-group-item pt-0 pb-3">
            <span class="fs-1 fw-medium text-success">Login</span>
          </li>
          <form method="post" action="{%url 'Accounts:login_user'%}">
            {% csrf_token %}
            <li class="list-group-item">
              <div class="form-floating">
                <input
                  type="text"
                  class="form-control"
                  name="username"
                  placeholder="abcd1234$"
                />
                <label for="username">Username</label>
              </div>
            </li>
            <li class="list-group-item">
              <div class="form-floating">
                <input
                  type="password"
                  class="form-control"
                  name="password"
                  placeholder="Password"
                />
                <label for="password">Password</label>
              </div>
            </li>
            <li class="list-group-item" id="login-btn">
              <input
                class="btn btn-lg btn-success px-4"
                type="submit"
                value="Login"
              />
            </li>
            <li class="list-group-item py-1">
              <span>
                Don't have an account?
                <a class="btn btn-sm btn-outline-success" href="{% url 'Accounts:register' %}"> Register here </a>
              </span>
            </li>
            <div class="form-group">
              {% for message in messages %}
              <div
                class="alert alert-danger"
                style="width: fit-content"
                role="alert"
              >
                {{message}}
              </div>
              {% endfor %}
            </div>
          </form>
        </ul>
      </div>
    </div>
  </div>
</html>
{% endblock content %}

Accounts/templates/Accounts/register.html
{% extends 'base.html' %} {% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Register</title>
  <style>
    html,
    body {
      height: 100%;
    }

    .centre-parent {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 85%;
    }

    .form-control:focus {
      border-color: rgb(6, 175, 116);
      box-shadow: 0 0 5px rgb(0, 74, 46) !important;
    }

    .card,
    .card li {
      width: fit-content;
      background-color: rgb(197, 234, 219);
    }

    .form-floating {
      width: fit-content;
      display: flex;
      justify-content: center;
      padding: 0;
    }

    .list-group li {
      padding: 2vh 0;
    }

    .form-floating label {
      margin-left: 0%;
    }

    .card-body {
      width: fit-content;
    }

    form {
      display: flex;
      justify-content: center;
      flex-direction: column;
      align-items: center;
    }

    .list-group-item {
      border: none;
    }

    #signup-btn {
      width: 100%;
    }
  </style>
</head>
<div class="centre-parent">
  <div class="card container">
    <div class="card-body px-5 mx-4">
      <ul class="list-group list-group-flush text-center">
        <li class="list-group-item">
          <span class="fs-2 fw-medium text-success">Sign Up</span>
        </li>
        <form method="post" action="{%url 'Accounts:register'%}">
          {% csrf_token %}
          <li class="list-group-item">
            <div class="form-floating">
              <input type="email" class="form-control" name="email" placeholder="20eumc100@skcet.ac.in" />
              <label for="email">Email Address</label>
            </div>
          </li>
          <li class="list-group-item">
            <div class="form-floating">
              <input type="password" class="form-control" name="password" placeholder="Password" />
              <label for="password">Password</label>
            </div>
          </li>
          <li class="list-group-item">
            <div class="form-floating">
              <input type="password" class="form-control" name="confirm_password" placeholder="Password" />
              <label for="confirm_password">Confirm Password</label>
            </div>
          </li>
          <li class="list-group-item">
            <div class="form-floating">
              <input type="text" class="form-control" name="first_name" placeholder="First Name" />
              <label for="first_name">First Name</label>
            </div>
          </li>
          <li class="list-group-item">
            <div class="form-floating">
              <input type="text" class="form-control" name="last_name" placeholder="Last Name" />
              <label for="last_name">Last Name</label>
            </div>
          </li>
          <li class="list-group-item">
            <div class="form-floating">
              <input type="text" class="form-control" name="username" placeholder="abcd1234$" />
              <label for="username">Username</label>
            </div>
          </li>
          <li class="list-group-item" id="signup-btn">
            <input class="btn btn-lg btn-success px-4" type="submit" value="Submit" />
          </li>
          <div class="form-group">
            {% for message in messages %}
            <div class="alert alert-danger" style="width: fit-content" role="alert">
              {{message}}
            </div>
            {% endfor %}
          </div>
        </form>
      </ul>
    </div>
  </div>
</div>

</html>
{% endblock content %}

Attendance/templates/Attendance/detail.html
{% extends 'base.html' %}

{% block content %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Attendance</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <style>
        #table-success {
            color: rgb(0, 88, 8);
            font-weight: 500;
        }

        #table-danger {
            color: rgb(169, 17, 17);
            font-weight: 500;
        }

        .table-status {
            font-weight: bolder;
            font-size: 115%;
        }

        table {
            text-align: center;
        }

        .card {
            border-radius: 12px;
        }
    </style>
</head>

<body>
    <div class="table-responsive container p-0 card my-3">
        <table class="table table-striped table-light table-hover table-bordered">
            <thead class="table-light">
                <tr>
                    <th scope="col">#</th>
                    {% for key in data_list.0 %}
                    <th scope="col">{{key}}</th>
                    {%endfor%}
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for data in data_list%}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    {% for value in data.values %}
                    {% if value == "Present" %}
                    <td class="table-success" id="table-success">{{value}}</td>
                    {% elif value == "Absent" %}
                    <td class="table-danger" id="table-danger">{{value}}</td>
                    {% elif value == True %}
                    <td class="table-success table-status" id="table-success">Present</td> {% elif value == "Absent" %}
                    {% elif value == False %}
                    <td class="table-danger table-status" id="table-danger">Absent</td>
                    {% else %}
                    <td>{{value}}</td>
                    {%endif%}
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>
{% endblock %}

Attendance/templates/Attendance/index.html
{% extends 'base.html' %}

{% block content %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Attendance</title>
  <style>
    #list-group{
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center ;
    }
    .list-group-item{
      display: flex;
      align-items: center;
      justify-content: center;
      border-radius: 6px;
    }
  </style>
</head>

<body>
  <div class="list-group list-group-flush list-group-item-success my-3" id="list-group" data-bs-theme="light" >
    {% for date in date_list%}
      <a href="{{date.date_id}}" class="list-group-item my-3 w-25 list-group-item-action">{{date}}</a>
    {%endfor%}
</body>
</html>
{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Logly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar" style="background-color: #313132;" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'Attendance:index' %}">
                {% load static %}
                <img src="{% static 'Attendance/bookmark.svg' %}" alt="Logo" width="30" height="24"
                    class="d-inline-block align-text-top">
                LogMe
            </a>
        </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>
    <style>
        html,
        body {
            height: 100%;
        }

        .centre-element {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 95%;
        }

        .list-group-item {
            border-style: none;
            display: flex;
            justify-content: center;
        }
    </style>
</head>
<div class="container centre-element">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <span class="fs-1 fw-bold text-success">
                Log Me - A smart attendance system
            </span>
        </li>
        <li class="list-group-item">
            <a type="button" class="btn btn-lg px-5 py-2 btn-success" href="{%url 'Attendance:index'%}">
                Go
            </a>
        </li>
    </ul>
</div>

</html>
{% endblock content %}